# Default values for stash-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""
image:
  # Docker registry used to pull MySQL addon image
  registry: stashed
  # Docker image used to backup/restore MySQL database
  repository: stash-mysql
  # Tag of the image that is used to backup/restore MySQL database.
  # This is usually same as the database version it can backup.
  tag: v2020.12.17
# optional argument to send mysqldump or mysql command
backup:
  # Arguments to pass to `mysqldump` command  during bakcup process
  args: "--all-databases"
restore:
  # Arguments to pass to `mysql` command during restore process
  args: ""
# Number of seconds to wait for the database to be ready before backup/restore process.
waitTimeout: 300
