# Default values for stash-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  registry: stashed
  repository: stash-mysql
  tag: "8.0.14"

# optional argument to send mysqldump or mysql command
backup:
  args: "--all-databases"
restore:
  args: ""
