apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: mysql-restore-{{- .Chart.Version }}
  labels:
    {{- include "stash-mysql.labels" . | nindent 4 }}
spec:
  image: {{ .Values.docker.registry }}/{{ .Values.docker.image }}:{{ .Values.docker.tag }}
  args:
  - restore-mysql
  # setup information
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --rest-server-url=${REPOSITORY_URL:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret
  - --scratch-dir=/tmp
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0} # 0 indicates use default connection limit
  - --hostname=${HOSTNAME:=}
  - --source-hostname=${SOURCE_HOSTNAME:=}
  - --mysql-args=${myArgs:={{ .Values.restore.myArgs }}} # optional arguments pass to mysql command
  # target information
  - --namespace=${NAMESPACE:=default}
  - --app-binding=${TARGET_NAME:=}
  - --snapshot=${RESTORE_SNAPSHOTS:=}
  # output & metric information
  - --output-dir=${outputDir:=}
  - --metrics-enabled={{ .Values.metrics.enabled }}
  - --metrics-pushgateway-url=${PROMETHEUS_PUSHGATEWAY_URL:=}
  {{- if .Values.metrics.labels }}
  - --metrics-labels={{ .Values.metrics.labels | quote }}
  {{- end }}
  volumeMounts:
  - name: ${secretVolume}
    mountPath: /etc/repository/secret
